#!/usr/bin/env python3
"""Diagnose test failures and recover generated code."""

from pathlib import Path
from recover_and_test import write_generated_code_to_disk, run_tests_and_reload
from coding_agent.test_runner import run_pytest


def diagnose_from_result(result: dict) -> None:
    """Diagnose issues from workflow result and fix them.
    
    Args:
        result: Result dictionary from workflow.run()
    """
    print("=" * 70)
    print("DIAGNOSIS: Why tests failed")
    print("=" * 70)
    
    # Check if code was generated
    cluster_modules = result.get("generated_cluster_modules", {})
    test_files = result.get("generated_test_files", {})
    
    print(f"\n1. Code Generation Status:")
    print(f"   Generated modules: {len(cluster_modules)}")
    print(f"   Generated test files: {len(test_files)}")
    
    if cluster_modules:
        print(f"   Module names: {list(cluster_modules.keys())}")
    if test_files:
        print(f"   Test file names: {list(test_files.keys())}")
    
    # Check if files exist on disk
    parsers_dir = Path("time_parser/parsers")
    tests_dir = Path("time_parser/tests")
    
    print(f"\n2. Files on Disk:")
    parser_files = [f.name for f in parsers_dir.glob("*.py") if f.name != "__init__.py"]
    test_files_on_disk = [f.name for f in tests_dir.glob("test_*.py")]
    
    print(f"   Parser modules on disk: {len(parser_files)}")
    if parser_files:
        print(f"   Files: {parser_files}")
    else:
        print(f"   ⚠️  NO PARSER MODULES FOUND ON DISK!")
    
    print(f"   Test files on disk: {len(test_files_on_disk)}")
    if test_files_on_disk:
        print(f"   Files: {test_files_on_disk}")
    else:
        print(f"   ⚠️  NO TEST FILES FOUND ON DISK!")
    
    # Check test results
    test_results = result.get("test_results", {})
    print(f"\n3. Test Results:")
    print(f"   All passed: {test_results.get('all_passed', 'N/A')}")
    print(f"   Return code: {test_results.get('returncode', 'N/A')}")
    
    if test_results.get("test_output"):
        print(f"\n   Test Output (first 500 chars):")
        print(f"   {test_results['test_output'][:500]}")
    
    if test_results.get("test_errors"):
        print(f"\n   Test Errors:")
        print(f"   {test_results['test_errors']}")
    
    # Diagnosis
    print(f"\n4. Diagnosis:")
    if not cluster_modules:
        print("   ❌ PROBLEM: No code was generated by ACT node")
        print("   → Check ACT node execution and LLM response parsing")
    elif not parser_files:
        print("   ❌ PROBLEM: Code was generated but files weren't written to disk")
        print("   → This is the issue! Files need to be recovered from state")
    elif not test_files_on_disk:
        print("   ❌ PROBLEM: Test files weren't written to disk")
        print("   → This is the issue! Test files need to be recovered from state")
    else:
        print("   ✓ Files exist on disk")
        if not test_results.get("all_passed"):
            print("   ❌ PROBLEM: Tests are failing (code issues)")
            print("   → Check test output above for specific failures")
    
    # Fix if possible
    print(f"\n5. Attempting Fix:")
    if cluster_modules and test_files and (not parser_files or not test_files_on_disk):
        print("   → Recovering generated code from state and writing to disk...")
        try:
            write_generated_code_to_disk(cluster_modules, test_files)
            print("   ✓ Files written successfully!")
            
            # Now run tests
            print("\n   → Running tests...")
            test_results = run_tests_and_reload()
            
            if test_results['all_passed']:
                print("\n" + "=" * 70)
                print("✅ SUCCESS! All tests passed and parser is updated.")
                print("=" * 70)
            else:
                print("\n" + "=" * 70)
                print("⚠️  Tests still failing. Check output above for details.")
                print("=" * 70)
        except Exception as e:
            print(f"   ❌ Failed to recover: {e}")
            import traceback
            traceback.print_exc()
    elif not cluster_modules:
        print("   ❌ Cannot fix: No generated code found in result")
        print("   → Need to rerun the workflow")
    else:
        print("   → Files already exist, running tests to check status...")
        test_results = run_tests_and_reload()
        if test_results['all_passed']:
            print("\n✅ All tests passed!")
        else:
            print("\n⚠️  Tests are still failing. Check output above.")


if __name__ == "__main__":
    print("Usage: Call diagnose_from_result(result) with your workflow result")
    print("Example:")
    print("  from diagnose_and_fix import diagnose_from_result")
    print("  result = workflow.run(initial_state=initial_state)")
    print("  diagnose_from_result(result)")
